# Generated by Django 5.1.6 on 2025-03-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkiapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Изображение'),
        ),
    ]
